version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "Application/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "Application/build.gradle" }}
      - run:
          name: Run Tests
          command: |
                   cd kotlinApp
                   ./gradlew test
      - run:
          name: Run Android Lint
          command: |
                   cd kotlinApp
                   ./gradlew lint
          when: always
      - run:
          name: Run ktint
          command: |
                   git clone --depth 1 git@github.com:mimimimichang/tools.git
                   tools/ktlint/ktlint kotlinApp/Application/src/**/*.kt --reporter=checkstyle,output=kotlinApp/Application/build/reports/ktlint.xml
          when: always
      - run:
          name: Run detekt
          command: |
                   java -jar tools/detekt/detekt-cli-1.0.0.RC9-all.jar -i kotlinApp/Application/src -r xml:kotlinApp/Application/build/reports/detekt.xml --debug --parallel
          when: always
      - store_artifacts:
          path: kotlinApp/Application/build/reports
          destination: reports
      - store_test_results:
          path: kotlinApp/Application/build/test-results
